name: Delete dev packages and releases

on:
  workflow_call:
    inputs:
      tag:
        description: 'Tag to delete'
        required: true
        type: string
        
        
permissions:
  id-token: write
  contents: write
  packages: write
  
  
jobs:          
  delete:
    runs-on: ubuntu-latest
    steps:
    
      - name: Print next tag version
        run: |
          echo "Tag ${{inputs.tag}} will be deleted!"     
          
      - name: Get version id of existing package version
        continue-on-error: true
        run: |
          RESPONSE=$(curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/orgs/hugomachadoOrg/packages/npm/fork-ast-cli-javascript-wrapper/versions)
          
          arraylength=${#RESPONSE[@]}    
          
          echo "LENGTH ${arraylength}"
          
          for (( i=0; i<${arraylength}; i++ ));
          do
            echo "index: $i, value: ${RESPONSE[$i]}"
          done
