name: Javascript Wrapper Release

on:
  workflow_call:
    inputs:
      tag:
        description: 'Tag to delete'
        required: true
        type: string
        
        
permissions:
  id-token: write
  contents: write
  packages: write
  
  
jobs:          
  delete:
    runs-on: ubuntu-latest
    steps:
    
      - name: Get version id of existing package version
        continue-on-error: true
        run: |
          RESPONSE=$(curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" "https://api.github.com/orgs/hugomachadoOrg/packages/npm/fork-ast-cli-javascript-wrapper/versions" | jq '.[]|select(.name=="${{inputs.tag}}")|.id')

          echo "VERSION_ID=${RESPONSE}" >> $GITHUB_ENV

      - name: Print VERSION_ID
        run: echo Version Id= ${{env.VERSION_ID}}

       # DELETE NPM PACKAGES WHICH CONTAINS NIGHTLY IN THE NAME
      - name: Delete nightly npm package
        if: env.VERSION_ID != ''
        run: |
          curl -L -X DELETE -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" "https://api.github.com/orgs/hugomachadoOrg/packages/npm/fork-ast-cli-javascript-wrapper/versions/${{env.VERSION_ID}}"

      # DELETE RELEASES AND TAGS WHICH CONTAINS NIGHTLY IN THE NAME
      - name: Delete nightly release and tag
        continue-on-error: true
        uses: dev-drprasad/delete-older-releases@v0.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          keep_latest: 0
          delete_tag_pattern: ${{inputs.tag}}
          delete_tags: true
